finalProject/Areas/Admin/Controllers/DoctorController.cs
using Business.Services.Intefaces;
using Entities.Dtos.ResHistory;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

[Area("admin")]
[Authorize(Roles = "admin")]


public class DoctorController : Controller
{
    private readonly IDoctorService _service;
    private readonly IPositionService _position;
    private readonly IResHistoryService _history;

    public DoctorController(IDoctorService service, IPositionService position, IResHistoryService history)
    {
        _service = service;
        _position = position;
        _history = history;
    }

    public async Task<IActionResult> Index(int currentpage = 1, int take = 5)
    {
        List<DoctorGetDto> getDtos = await _service.GetAllAsync(d=>!d.IsDeleted);
        getDtos = getDtos
                .OrderByDescending(d => d.Id)
                .Skip((currentpage - 1) * take)
                .Take(take)
                .ToList();
        int pageCount = (int)Math.Ceiling((decimal)getDtos.Count / take);
        if (pageCount == 0) pageCount = 1;
        PaginationDto<DoctorGetDto> pagination = new PaginationDto<DoctorGetDto>
        {
            Models = getDtos,
            CurrentPage = currentpage,
            PageCount = pageCount,
            Next = currentpage < pageCount,
            Previous = currentpage > 1
        };

        return View(pagination);
    }
    public async Task<IActionResult> Create()
    {
        ViewBag.Positions = await _position.GetAllAsync();
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> Create(DoctorPostDto postDto)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.Positions = await _position.GetAllAsync();
            return View();
        }
        if (!postDto.formFile.ContentType.Contains("image"))
        {
            ModelState.AddModelError("Formfile", "please send image");
            ViewBag.Positions = await _position.GetAllAsync();
            return View(postDto);
        }
        await _service.CreateAsync(postDto);
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Update(int id)
    {
        DoctorGetDto getDto = await _service.GetbyId(id);
        if (getDto == null) return NotFound();
        if (getDto.IsDeleted == true) { return NotFound(); }
        DoctorUpdateDto updateDto = new DoctorUpdateDto { getDto = getDto };
        ViewBag.Positions = await _position.GetAllAsync();
        return View(updateDto);
    }
    [HttpPost]
    public async Task<IActionResult> Update(DoctorUpdateDto updateDto)
    {
       var result= await _service.UpdateAsync(updateDto);
        if (!result)
        {
            ViewBag.Positions = await _position.GetAllAsync();

            return View(updateDto);
        }
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Delete(int id)
    {
      var result=  await _service.DeleteAsync(id);
        if(!result) return NotFound();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Detail(int id)
    {
        DoctorGetDto doctor = await _service.GetbyId(id);
        if (doctor == null) { return NotFound(); };
        return View(doctor);
    }
    public async Task<IActionResult> GetAll(int currentpage = 1, int take = 5)
    {
        List<DoctorGetDto> getDtos = await _service.GetAllAsync(d => d.IsDeleted || !d.IsDeleted|| (d.IsDeleted && !d.IsDeleted));
        if (getDtos == null) return View();
        getDtos = getDtos
                .OrderByDescending(d => d.Id)
                .Skip((currentpage - 1) * take)
                .Take(take)
                .ToList();
        int pageCount = (int)Math.Ceiling((decimal)getDtos.Count / take);
        if (pageCount == 0) pageCount = 1;
        PaginationDto<DoctorGetDto> pagination = new PaginationDto<DoctorGetDto>
        {
            Models = getDtos,
            CurrentPage = currentpage,
            PageCount = pageCount,
            Next = currentpage < pageCount,
            Previous = currentpage > 1
        };

        return View(pagination);
    }
    public async Task<IActionResult> History(int currentpage = 1, int take = 5)
    {
        List<ResGetDto> getDtos = await _history.GetAllAsync();
        if(getDtos==null) return View();
        getDtos = getDtos
               .OrderByDescending(d => d.Id)
               .Skip((currentpage - 1) * take)
               .Take(take)
               .ToList();
        int pageCount = (int)Math.Ceiling((decimal)getDtos.Count / take);
        if (pageCount == 0) pageCount = 1;
        PaginationDto<ResGetDto> pagination = new PaginationDto<ResGetDto>
        {
            Models = getDtos,
            CurrentPage = currentpage,
            PageCount = pageCount,
            Next = currentpage < pageCount,
            Previous = currentpage > 1
        };

        return View(pagination);
    }

}

finalProject/Areas/Admin/Controllers/MessageController.cs
using Business.Services.Intefaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

[Area("admin")]
[Authorize(Roles = "admin")]

public class MessageController : Controller
{
    private readonly IMessageService _service;

    public MessageController(IMessageService service)
    {
        _service = service;
    }

    public async Task<IActionResult> Index(int currentpage = 1, int take = 6)
    {
        List<MessageGetDto> messages = await _service.GetAllAsync(m => !m.IsDeleted);
        if (messages == null) { return View(); }
        messages = messages
                 .OrderByDescending(d => d.Id)
                .Skip((currentpage - 1) * take)
                .Take(take)
                .ToList();
        int pageCount = (int)Math.Ceiling((decimal)messages.Count / take);
        if (pageCount == 0) pageCount = 1;
        PaginationDto<MessageGetDto> pagination = new PaginationDto<MessageGetDto>
        {
            Models = messages,
            CurrentPage = currentpage,
            PageCount = pageCount,
            Next = currentpage < pageCount,
            Previous = currentpage > 1
        };
        return View(pagination);
    }
    public async Task<IActionResult> Delete(int id)
    {
      var result=  await _service.DeleteAsync(id);
        if (!result) return NotFound();
        return RedirectToAction(nameof(Index));
    }
    public async Task<IActionResult> Deleted()
    {
        List<MessageGetDto> getDtos = await _service.GetAllAsync(m => m.IsDeleted);
        if (getDtos == null) return View();
        return View(getDtos);
    }
    public async Task<IActionResult> Restore(int id)
    {
      var result=  await _service.RestoreAsync(id);
        if (!result) return NotFound();
        return RedirectToAction(nameof(Deleted));
    }

}

finalProject/Controllers/MessageController.cs
using AutoMapper;
using Business.Services.Intefaces;
using Core.Entities.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;

namespace finaProject.Controllers
{
    public class MessageController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly IMessageService _service;

        public MessageController( UserManager<AppUser> userManager, IMessageService service)
        {

            _userManager = userManager;
            _service = service;
        }
        [HttpPost]
        public async Task<IActionResult> Send(MessagePostDto postDto)
        {
            if (!ModelState.IsValid)
            {
                return Json("Make sure you fill in the fields correctly");
            }
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Contact",postDto);
            }
            AppUser user=await _userManager.FindByEmailAsync(postDto.Email);
            if(user == null)
            {
                return Json("Make sure you fill in the fields correctly");
            }
            postDto.UserName = user.UserName;
            await _service.CreateAsync(postDto);
            return Json(new { status = 200 });
        }
    }
}

finalProject/Areas/Admin/Views/Message/Deleted.cshtml
@{
    ViewData["Title"] = "Deleted";
}
@model List<MessageGetDto>
<div class="row">
    @if (Model != null)
    {
        @foreach (var item in Model)
        {
            <div class="card col-md-6 m-2" style="width: 20rem; height: 22rem">
                <div class="card-body">
                    <h4 class="card-title" style=" text-align:center"> @item.UserName</h4>
                    <br>
                    <h5 style=" text-align:center">Subject:</h5>

                    <h5 class="card-text"> @item.Subject</h5>
                    <br>
                    <h5 style=" text-align:center">Letter:</h5>

                    <h5 class="card-text">@item.Letter</h5>
                    <br>
                    <h5 style=" text-align:center">Email:</h5>

                    <h5 class="card-text">@item.Email</h5>
                    <br>

                    <a asp-action="Restore" asp-controller="Message" asp-route-id="@item.Id" class="btn btn-danger">Restore Message</a>
                </div>
            </div>
        }
    }
</div>

finalProject/Areas/Admin/Views/Message/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model PaginationDto<MessageGetDto>
<a asp-action="Deleted" asp-controller="Message"><i class="fa-regular fa-trash-can fa-2x"></i></a>
<div class="row">
    @if (Model != null)
    {
        @foreach (var item in Model.Models)
        {
            <div class="card col-md-6 m-2" style="width: 20rem; height: 22rem">
                <div class="card-body">
                    <h4 class="card-title" style=" text-align:center"> @item.UserName</h4>
                    <br>
                    <h5 style=" text-align:center">Subject:</h5>

                    <h5 class="card-text"> @item.Subject</h5>
                    <br>
                    <h5 style=" text-align:center">Letter:</h5>

                    <h5 class="card-text" >@item.Letter</h5>
                    <br>
                    <h5 style=" text-align:center">Email:</h5>

                    <h5 class="card-text">@item.Email</h5>
                    <br>

                    <a asp-action="Delete" asp-controller="Message" asp-route-id="@item.Id" class="btn btn-danger">Delete Message</a>
                </div>
            </div>
        }
    }
</div>
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item @(Model.Previous?"":"disabled")">
            <a class="page-link" asp-controller="Doctor" asp-action="Index" asp-route-currentpage="@(Model.CurrentPage-1)" tabindex="-1">Previous</a>
        </li>
        @for (int i = 1; i < Model.PageCount + 1; i++)
        {
            <li class="page-item @(i==Model.CurrentPage?"active":"") "><a class="page-link" asp-controller="Doctor" asp-action="Index" asp-route-currentpage="@i">@i</a></li>

        }

        <li class="page-item @(Model.Next?"":"disabled")">
            <a class="page-link" asp-controller="Doctor" asp-action="Index" asp-route-currentpage="@(Model.CurrentPage+1)">Next</a>
        </li>
    </ul>
</nav>