finalProject/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;


namespace finaProject.Controllers
{
    public class AboutController : Controller
    {

        public async Task<IActionResult> Index()
        {
            return View();
        }
    }
}

finalProject/Controllers/ContactController.cs
using AutoMapper;
using Business.Services.Intefaces;
using Microsoft.AspNetCore.Mvc;

namespace finaProject.Controllers
{
    public class ContactController : Controller
    {
        private readonly ISettingService _service;

        public ContactController(ISettingService service)
        {
            _service = service;
        }
        public async Task< IActionResult> Index(MessagePostDto? postDto)
        {
            if (postDto.Letter != null)
            {
              ModelState.AddModelError("", "Please first login or register");

            }
            SettingGetDto getDto = await _service.Get();
            ContactGetDto contact = new ContactGetDto { Setting = getDto };
            return View(contact);
        }
    }
}

finalProject/Controllers/SearchController.cs
using AutoMapper;
using Business.Services.Intefaces;
using Microsoft.AspNetCore.Mvc;

namespace finaProject.Controllers
{
    public class SearchController : Controller
    {

        private readonly IDoctorService _service;
        public SearchController(IDoctorService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(DoctorSearchDto? searchDto)
        {
            if(searchDto.getDtos == null)
            {
                List<DoctorGetDto> getDtos = await _service.GetAllAsync(d => !d.IsDeleted);
                getDtos = getDtos.Take(4).ToList();
                searchDto.getDtos=getDtos;
                searchDto.count = getDtos.Count;
                return View(searchDto);
            }
            return View(searchDto);
        }
        [HttpPost]
        public async Task<IActionResult> Result(DoctorSearchDto searchDto)
        {
            List<DoctorGetDto> getDtos = await _service.GetAllAsync(d => d.Name == searchDto.postDto.Name, "Icons");
            if (getDtos == null)
            {
                return RedirectToAction(nameof(Index));
            }
            searchDto.getDtos= getDtos;
            return View("Index", searchDto);
        }
        public async Task<IActionResult> LoadMore(int skip)
        {
            List<DoctorGetDto> getDtos1 = await _service.GetAllAsync(d => !d.IsDeleted);
            getDtos1 = getDtos1.Skip(skip).Take(3).ToList();
            return PartialView("_TeamPartialView", getDtos1);

        }
    }
}

finalProject/Controllers/TeamController.cs
using AutoMapper;
using Business.Services.Intefaces;
using Entities.Concrete.Models;
using Entities.Dtos.ResHistory;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NuGet.Protocol.Core.Types;

namespace finaProject.Controllers
{
    public class TeamController : Controller
    {
        private readonly IDoctorService _service;
        private readonly IResHistoryService _res;
        private readonly IMapper _mapper;

        public TeamController(IDoctorService service, IResHistoryService res, IMapper mapper)
        {
            _service = service;
            _res = res;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Rezerv(int id, string time, string user)
        {
            DoctorGetDto get = await _service.Get(d => d.Id == id, "Icons", "rezervs");
            foreach (var item in get.rezervs)
            {
                if (item.Time == time)
                {

                    item.Busy = !item.Busy;
                    item.UserEmail = user;
                    ResHistory history= new ResHistory() { UserEmail= user,date=DateTime.Now,Doctor=_mapper.Map<Doctor>(get)};
                    await _service.AddHistory(history,get.Id);
                }
            };
            DoctorUpdateDto updateDto = new DoctorUpdateDto { getDto = get };
            await _service.UpdateAsync(updateDto);
            return RedirectToAction("Index", "Reservation");
        }
    }
}

finalProject/Views/Shared/_Layout.cshtml
@inject Business.Services.Intefaces.ISettingService Settingg
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>MEDINOVA - Hospital Website Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="~/assets/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&family=Roboto:wght@400;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A==" crossorigin="" />

    <!-- Libraries Stylesheet -->
    <link href="~/assets/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/assets/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/assets/css/style.css" rel="stylesheet">
</head>

<body>
    <!-- Topbar Start -->
    <div class="container-fluid py-2 border-bottom d-none d-lg-block">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-lg-start mb-2 mb-lg-0">
                    <div class="d-inline-flex align-items-center">
                        <a class="text-decoration-none text-body pe-3" href=""><i class="bi bi-telephone me-2"></i>  @Settingg.Get().Result.Phone </a>
                        <span class="text-body">|</span>
                        <a class="text-decoration-none text-body px-3" href=""><i class="bi bi-envelope me-2"></i> @Settingg.Get().Result.Email</a>
                    </div>
                </div>
                <div class="col-md-6 text-center text-lg-end">
                    <div class="d-inline-flex align-items-center">
                        @foreach (var item in Settingg.Get().Result.Icons)
                        {
                            <a class="text-body px-2" href=@item.IconUrl>
                                @Html.Raw(item.IconTag)
                            </a>
                        }

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->
    <!-- Navbar Start -->
    <div class="container-fluid sticky-top bg-white shadow-sm">
        <div class="container">
            <nav class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand">
                    <h1 class="m-0 text-uppercase text-primary">@Html.Raw(Settingg.Get().Result.LogoIcon) @Settingg.Get().Result.Logo</h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0">
                        <a asp-action="Index" asp-controller="Home" class="nav-item nav-link">Home</a>
                        <a asp-controller="About" asp-action="Index" class="nav-item nav-link">About</a>
                        <a asp-controller="Service" asp-action="Index" class="nav-item nav-link">Service</a>
                        <a asp-controller="Reservation" asp-action="Index" class="nav-item nav-link">Reservation</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a asp-controller="Team" asp-action="Index" class="dropdown-item">The Team</a>
                                <a asp-action="Index" asp-controller="Testimonial" class="dropdown-item">Testimonial</a>
                                <a asp-action="Index" asp-controller="Search" class="dropdown-item">Search</a>
                            </div>
                        </div>
                        <a asp-action="Index" asp-controller="Contact" class="nav-item nav-link">Contact</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Account</a>
                            <div class="dropdown-menu m-0">
                                @if (!User.Identity.IsAuthenticated)
                                {
                                    <a asp-action="Login" asp-controller="Account" class="dropdown-item">Login</a>
                                    <a asp-controller="Account" asp-action="Register" class="dropdown-item">Register</a>
                                }
                                else
                                {
                                    <a asp-action="Logout" asp-controller="Account" class="dropdown-item">Logout</a>
                                }
                            </div>
                        </div>
                        @if (User.Identity.IsAuthenticated)
                        {
                        <a asp-action="Index" asp-controller="Reshistory" class="nav-item nav-link">Reservation History</a>
                            
                        }

                    </div>
                </div>
            </nav>
        </div>
    </div>
    <!-- Navbar End -->
    @RenderBody()
    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light mt-5 py-5">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-4 col-md-6">
                    <h4 class="d-inline-block text-primary text-uppercase border-bottom border-5 border-secondary mb-4">Get In Touch</h4>
                    <p class="mb-2"><i class="fa fa-map-marker-alt text-primary me-3"></i>@Settingg.Get().Result.Address</p>
                    <p class="mb-2"><i class="fa fa-envelope text-primary me-3"></i>@Settingg.Get().Result.Email</p>
                    <p class="mb-0"><i class="fa fa-phone-alt text-primary me-3"></i>@Settingg.Get().Result.Phone</p>
                </div>
                <div class="col-lg-4 col-md-6">
                    <h4 class="d-inline-block text-primary text-uppercase border-bottom border-5 border-secondary mb-4">Quick Links</h4>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-light mb-2" asp-action="Index" asp-controller="Home"><i class="fa fa-angle-right me-2"></i>Home</a>
                        <a class="text-light mb-2" asp-action="Index" asp-controller="About"><i class="fa fa-angle-right me-2"></i>About Us</a>
                        <a class="text-light mb-2" asp-action="Index" asp-controller="Contact"><i class="fa fa-angle-right me-2"></i>Our Services</a>
                        <a class="text-light mb-2" asp-action="Index" asp-controller="Team"><i class="fa fa-angle-right me-2"></i>Meet The Team</a>
                        @*                        <a class="text-light mb-2" href="#"><i class="fa fa-angle-right me-2"></i>Latest Blog</a>
                        *@                        <a class="text-light" asp-action="Index" asp-controller="Contact"><i class="fa fa-angle-right me-2"></i>Contact Us</a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <h4 class="d-inline-block text-primary text-uppercase border-bottom border-5 border-secondary mb-4">Newsletter</h4>

                    <h6 class="text-primary text-uppercase mt-4 mb-3">Follow Us</h6>
                    <div class="d-flex">
                        @foreach (var item in Settingg.Get().Result.Icons)
                        {
                            <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-2" href=@item.IconUrl>@Html.Raw(item.IconTag)</a>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->
    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="~/assets/lib/easing/easing.min.js"></script>
    <script src="~/assets/lib/waypoints/waypoints.min.js"></script>
    <script src="~/assets/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/assets/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/assets/js/main.js"></script>
</body>

</html>

finalProject/Views/Shared/_TeamPartialView.cshtml
@model List<DoctorGetDto>
@foreach (var item in Model)
{

    <div class="col-lg-6 team-item">
        <div class="row g-0 bg-light rounded overflow-hidden ">
            <div class="col-12 col-sm-7 h-100 ">
                <img class="~/assets/img-fluid h-100" src="~/assets/img/@item.Image" style="object-fit: cover;">
            </div>

            <div class="col-12 col-sm-5 h-100 d-flex flex-column">
                <div class="mt-auto p-4">
                    <h3>@item.Name</h3>
                    <h6 class="fw-normal fst-italic text-primary mb-4">@item.About</h6>
                    <p class="m-0">@item.About</p>
                </div>
                <div class="d-flex mt-auto border-top p-4">
                    @foreach (var icon in item.Icons)
                    {
                        if (icon.IconTag != null)
                        {

                            <a class="btn btn-lg btn-primary btn-lg-square rounded-circle me-3" href=@icon.IconUrl> @Html.Raw(icon.IconTag)</a>
                        }

                    }

                </div>
            </div>
        </div>
    </div>
}